start
Roki2221/project-TWELWEB pull request #11
Opened 2023-07-11 13:06 UTC by 102odua

2023-07-11 14:36 UTC, Roki2221 requested changes

2023-07-11 14:36 UTC, Roki2221 commented on src/css/modal.css
> +:root {
переписати всі селектори з тегів на  класи(деталі запінені в чаті групи)
перевірити на повторення стилів

2023-07-11 14:36 UTC, Roki2221 commented on src/partials/modal.html
> +<link
прибрати всі лінки, мета теги, весл код знаходиться в контейнері прописаний через section

2023-07-11 14:36 UTC, Roki2221 commented on src/partials/modal.html
> +      <input
додати мінімальну валідацію даних для введення за допомогою  атрибуту pattern

2023-07-11 19:33 UTC, 102odua commented on src/partials/modal.html
> +      <input
Паттерни виставив

2023-07-11 19:34 UTC, 102odua commented on src/partials/modal.html
> +<link
Зробив контейнер section

2023-07-12 22:59 UTC, Roki2221 approved these changes

2023-07-12 22:59 UTC, merged